version: "3.9"
services:
  web:
    build: .
    container_name: villa_rose_web
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: flask run --host=0.0.0.0

  db:
    image: postgres:18
    container_name: villa_rose_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  pgdata:
